// File-repository — all DB access for the native file storage system.
//
// Design notes:
//
//  - Blob bytes live in file_blobs, metadata in files (see migration 023).
//    Metadata-only queries (GetFile, ListFiles) never touch the BYTEA
//    column — keeping them cheap and fast — and the blob is only read
//    on demand via GetFileContent when a client streams or OCRs the file.
//
//  - CreateFile inserts the blob row and the files row inside a single
//    pgx.Tx so we can never end up with a dangling blob (no files row
//    pointing at it) or a dangling files row (blob_id pointing at a
//    missing blob). The tx also guarantees the size on files matches the
//    actual byte length written to file_blobs.
//
//  - DeleteFile deletes the files row first (RETURNING blob_id) and then
//    the blob row, both inside a tx, scoped by household_id. If the files
//    row is missing or belongs to a different household we affect zero
//    rows and return pgx.ErrNoRows — the caller can translate that to 404
//    without leaking whether the file exists in another household.
//
//  - Every method takes householdID and filters by it. This is the same
//    tenant-isolation pattern used by apps/api/internal/note/repo.go and
//    apps/api/internal/calendar/repo.go: a missing cross-tenant row is
//    indistinguishable from a missing same-tenant row.

package file

import (
	"context"
	"errors"
	"fmt"
	"strings"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"
)

// Repo provides read/write access to the file_blobs and files tables using a
// pgx connection pool. All queries are scoped to household_id to enforce
// tenant isolation, mirroring apps/api/internal/note/repo.go.
type Repo struct {
	pool *pgxpool.Pool
}

// NewRepo creates a new file repository backed by the given pool.
func NewRepo(pool *pgxpool.Pool) *Repo {
	return &Repo{pool: pool}
}

// CreateFile stores a new file: it inserts a file_blobs row with the raw
// bytes and then a files row with the metadata, both inside a single
// transaction. If either statement fails the whole operation rolls back so
// we never leave an orphaned blob or an orphaned files row.
//
// The caller must supply a fully-populated *File (BlobID is generated here
// if empty; ID is generated by the DB default). The returned *File reflects
// the persisted row (including DB-generated id, blob_id, timestamps, and
// the 'pending' default for ocr_status).
func (r *Repo) CreateFile(ctx context.Context, householdID uuid.UUID, f *File, data []byte) (*File, error) {
	tx, err := r.pool.BeginTx(ctx, pgx.TxOptions{})
	if err != nil {
		return nil, fmt.Errorf("create file: begin tx: %w", err)
	}
	defer tx.Rollback(ctx)

	// Insert the blob row first — files.blob_id references it.
	var blobID uuid.UUID
	err = tx.QueryRow(ctx,
		`INSERT INTO file_blobs (data, size)
		 VALUES ($1, $2)
		 RETURNING id`,
		data, len(data),
	).Scan(&blobID)
	if err != nil {
		return nil, fmt.Errorf("create file: insert blob: %w", err)
	}

	// Insert the metadata row referencing the blob we just created.
	var created File
	err = tx.QueryRow(ctx,
		`INSERT INTO files (household_id, blob_id, name, content_type, size, entity_type, entity_id, tags)
		 VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
		 RETURNING id, household_id, blob_id, name, content_type, size, entity_type, entity_id,
		           extracted_text, ocr_status, ocr_error, tags, created_at, updated_at`,
		householdID, blobID, f.Name, f.ContentType, int64(len(data)), f.EntityType, f.EntityID, f.Tags,
	).Scan(
		&created.ID, &created.HouseholdID, &created.BlobID, &created.Name, &created.ContentType,
		&created.Size, &created.EntityType, &created.EntityID, &created.ExtractedText,
		&created.OCRStatus, &created.OCRError, &created.Tags, &created.CreatedAt, &created.UpdatedAt,
	)
	if err != nil {
		return nil, fmt.Errorf("create file: insert metadata: %w", err)
	}

	if err := tx.Commit(ctx); err != nil {
		return nil, fmt.Errorf("create file: commit: %w", err)
	}
	return &created, nil
}

// GetFile returns the metadata for a single file by ID, scoped to the given
// household. The BYTEA payload is NOT selected — use GetFileContent to stream
// the raw bytes. Returns (nil, nil) when the file does not exist or belongs
// to a different household; callers MUST treat both cases as 404 so an
// attacker cannot distinguish "no such file" from "file exists but isn't
// yours" (matching note/repo.go and the CalDAV tenant-isolation pattern).
func (r *Repo) GetFile(ctx context.Context, householdID, id uuid.UUID) (*File, error) {
	rows, err := r.pool.Query(ctx,
		`SELECT id, household_id, blob_id, name, content_type, size, entity_type, entity_id,
		        extracted_text, ocr_status, ocr_error, tags, created_at, updated_at
		 FROM files
		 WHERE id = $1 AND household_id = $2`,
		id, householdID,
	)
	if err != nil {
		return nil, fmt.Errorf("get file: %w", err)
	}
	defer rows.Close()

	f, err := pgx.CollectOneRow(rows, pgx.RowToAddrOfStructByPos[File])
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, nil
		}
		return nil, fmt.Errorf("get file: collect: %w", err)
	}
	return f, nil
}

// GetFileContent returns the raw bytes of the blob backing the given file.
// The file is first looked up in the files table scoped by household_id (so
// a caller from another household cannot read another family's bytes), and
// then the blob is fetched by the blob_id stored on that files row.
//
// Returns (nil, nil) when the file does not exist or belongs to a different
// household — same not-found-vs-forbidden contract as GetFile.
func (r *Repo) GetFileContent(ctx context.Context, householdID, id uuid.UUID) ([]byte, error) {
	// Resolve the blob_id via the household-scoped files row so we never
	// read a blob that doesn't belong to the caller.
	var blobID uuid.UUID
	err := r.pool.QueryRow(ctx,
		`SELECT blob_id FROM files WHERE id = $1 AND household_id = $2`,
		id, householdID,
	).Scan(&blobID)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, nil
		}
		return nil, fmt.Errorf("get file content: resolve blob_id: %w", err)
	}

	var data []byte
	err = r.pool.QueryRow(ctx,
		`SELECT data FROM file_blobs WHERE id = $1`,
		blobID,
	).Scan(&data)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			// The files row existed but its blob is gone — a data-integrity
			// problem, not a normal 404. Surface it as an error so callers
			// can log it rather than silently returning "not found".
			return nil, fmt.Errorf("get file content: blob %s missing for file %s: %w", blobID, id, err)
		}
		return nil, fmt.Errorf("get file content: fetch blob: %w", err)
	}
	return data, nil
}

// ListFiles returns all files for a household, optionally narrowed to a
// specific (entity_type, entity_id) polymorphic association. Results are
// ordered newest-first to match the dashboard "recent files" use case
// (idx_files_household_created backs this ordering).
//
// When entityType and entityID are both non-empty the query is scoped to
// files attached to that entity; otherwise the entire household is listed.
// An empty result set returns a non-nil empty slice (not nil) so JSON
// marshalling produces [] rather than null.
func (r *Repo) ListFiles(ctx context.Context, householdID uuid.UUID, entityType string, entityID uuid.UUID) ([]*File, error) {
	var (
		query string
		args  []any
	)
	if entityType != "" && entityID != uuid.Nil {
		query = `SELECT id, household_id, blob_id, name, content_type, size, entity_type, entity_id,
		                extracted_text, ocr_status, ocr_error, tags, created_at, updated_at
		         FROM files
		         WHERE household_id = $1 AND entity_type = $2 AND entity_id = $3
		         ORDER BY created_at DESC`
		args = []any{householdID, entityType, entityID}
	} else {
		query = `SELECT id, household_id, blob_id, name, content_type, size, entity_type, entity_id,
		                extracted_text, ocr_status, ocr_error, tags, created_at, updated_at
		         FROM files
		         WHERE household_id = $1
		         ORDER BY created_at DESC`
		args = []any{householdID}
	}

	rows, err := r.pool.Query(ctx, query, args...)
	if err != nil {
		return nil, fmt.Errorf("list files: %w", err)
	}
	defer rows.Close()

	files, err := pgx.CollectRows(rows, pgx.RowToAddrOfStructByPos[File])
	if err != nil {
		return nil, fmt.Errorf("list files: collect: %w", err)
	}
	if files == nil {
		files = []*File{}
	}
	return files, nil
}

// DeleteFile removes both the files row and its backing file_blobs row in a
// single transaction, scoped to household_id. The files row is deleted first
// (RETURNING blob_id) and the blob row second; deleting in the opposite
// order would leave files referencing a missing blob mid-tx and would also
// violate the file_blobs→files FK direction.
//
// Returns pgx.ErrNoRows if the file does not exist or belongs to a different
// household — the caller can translate that to 404 without leaking
// cross-tenant existence.
func (r *Repo) DeleteFile(ctx context.Context, householdID, id uuid.UUID) error {
	tx, err := r.pool.BeginTx(ctx, pgx.TxOptions{})
	if err != nil {
		return fmt.Errorf("delete file: begin tx: %w", err)
	}
	defer tx.Rollback(ctx)

	var blobID uuid.UUID
	err = tx.QueryRow(ctx,
		`DELETE FROM files WHERE id = $1 AND household_id = $2 RETURNING blob_id`,
		id, householdID,
	).Scan(&blobID)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			// Nothing to delete — preserve the prior contract of returning
			// pgx.ErrNoRows for a missing file. The deferred Rollback is a
			// no-op since we never wrote anything.
			return pgx.ErrNoRows
		}
		return fmt.Errorf("delete file: delete metadata: %w", err)
	}

	if _, err = tx.Exec(ctx,
		`DELETE FROM file_blobs WHERE id = $1`,
		blobID,
	); err != nil {
		return fmt.Errorf("delete file: delete blob: %w", err)
	}

	if err := tx.Commit(ctx); err != nil {
		return fmt.Errorf("delete file: commit: %w", err)
	}
	return nil
}

// UpdateOCRStatus updates the OCR pipeline state for a file: it sets
// extracted_text and ocr_status, and (when provided) ocr_error. The update is
// scoped by household_id so a worker acting on behalf of one household
// cannot mutate another household's OCR state via a guessed file ID.
//
// Pass nil for extractedText to leave the column unchanged (useful when
// transitioning to 'processing' before any text has been extracted), and nil
// for ocrError to clear a previously-recorded error.
//
// Returns pgx.ErrNoRows if the file does not exist or is not owned by the
// given household.
func (r *Repo) UpdateOCRStatus(ctx context.Context, householdID, id uuid.UUID, ocrStatus string, extractedText *string, ocrError *string) error {
	tag, err := r.pool.Exec(ctx,
		`UPDATE files
		 SET ocr_status = $1,
		     extracted_text = COALESCE($2, extracted_text),
		     ocr_error = $3,
		     updated_at = NOW()
		 WHERE id = $4 AND household_id = $5`,
		ocrStatus, extractedText, ocrError, id, householdID,
	)
	if err != nil {
		return fmt.Errorf("update ocr status: %w", err)
	}
	if tag.RowsAffected() == 0 {
		return pgx.ErrNoRows
	}
	return nil
}

// UpdateFile patches the user-editable metadata of a file — its name and/or
// tags — scoped to household_id. It backs the PATCH /api/v1/files/{id}
// endpoint (task #1201's handler).
//
// Semantics:
//   - name == nil  → name column is left unchanged.
//   - name != nil  → name is set to *name (may be set to "" to clear it).
//   - tags == nil  → tags array is left unchanged.
//   - tags != nil  → tags array is replaced wholesale (pass an empty slice to
//     clear all tags). A nil element is not special; pgx encodes []string as a
//     text[].
//
// At least one of name / tags should be non-nil; the handler rejects an
// all-nil PATCH with 400 before reaching here.
//
// Returns the fully-populated updated *File, or (nil, nil) if the file does not
// exist or belongs to a different household — same not-found-vs-forbidden
// contract as GetFile so callers translate both to 404 without leaking
// cross-tenant existence.
func (r *Repo) UpdateFile(ctx context.Context, householdID, id uuid.UUID, name *string, tags []string) (*File, error) {
	// Build the SET clause dynamically so unset fields are not touched. This
	// avoids the nil-[]string encoding ambiguity that a COALESCE/CASE approach
	// would introduce (a nil slice marshals as '{}' under pgx, which would
	// wrongly wipe existing tags).
	setParts := []string{"updated_at = NOW()"}
	args := []any{householdID, id} // $1 = household_id, $2 = id
	next := 3
	if name != nil {
		setParts = append(setParts, fmt.Sprintf("name = $%d", next))
		args = append(args, *name)
		next++
	}
	if tags != nil {
		setParts = append(setParts, fmt.Sprintf("tags = $%d", next))
		args = append(args, tags)
		next++
	}

	query := fmt.Sprintf(`
		UPDATE files
		SET %s
		WHERE id = $2 AND household_id = $1
		RETURNING id, household_id, blob_id, name, content_type, size, entity_type, entity_id,
		          extracted_text, ocr_status, ocr_error, tags, created_at, updated_at`,
		strings.Join(setParts, ", "),
	)

	var updated File
	err := r.pool.QueryRow(ctx, query, args...).Scan(
		&updated.ID, &updated.HouseholdID, &updated.BlobID, &updated.Name, &updated.ContentType,
		&updated.Size, &updated.EntityType, &updated.EntityID, &updated.ExtractedText,
		&updated.OCRStatus, &updated.OCRError, &updated.Tags, &updated.CreatedAt, &updated.UpdatedAt,
	)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, nil
		}
		return nil, fmt.Errorf("update file: %w", err)
	}
	return &updated, nil
}
