apiVersion: v1
kind: Service
metadata:
  name: home-os-calendar
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - port: {{ .Values.calendar.port }}
    targetPort: {{ .Values.calendar.port }}
    protocol: TCP
    name: http
  selector:
    app: home-os-calendar
